### ISSUE TITLE
Projects to add!

### ISSUE THREAD

**Issue by jdan** [Khan/khan.github.io#1]
- [x] [guacamole](https://github.com/Khan/guacamole)
- [x] [structuredjs](https://github.com/Khan/structuredjs)
- [x] [i18nize_templates](https://github.com/Khan/i18nize_templates)
- [x] [khan-exercises](https://github.com/Khan/khan-exercises)
- [x] [gae_mini_profiler](https://github.com/Khan/gae_mini_profiler)

**Comment by IdrissDimson** [comment]
time to close?

**Comment by jdan** [comment]
Yep! Thanks :)
