### ISSUE TITLE
FAQ section? - E.g.: how to run dev/prod Khan Academy

### ISSUE THREAD

**Issue by SamuelMarks** [Khan/khan.github.io#2]
Any chance for adding a FAQ section to this site?

Given that it's a collection of open-source projects at Khan Academy, I'm sure many people go to your GitHub seeking to run their own Khan Academy (OpenEdX style).

Would be good if that question was answered, e.g.: with a link to a blog/tutorial showing how to deploy.

Thanks!

**Comment by sophiebits** [comment]
Sorry, we don't support any way to "run your own Khan Academy".

**Comment by SamuelMarks** [comment]
Ah okay thanks for clarifying.

Just spent some time looking through your docs and projects but this was never mentioned. Found a [project for running Khan Academy offline](https://learningequality.org/ka-lite), and [khan-exercises docs](http://khan-exercises.readthedocs.io/en/latest) which told me that:

> This framework, together with the exercises themselves, can be used completely independently of the Khan Academy application

Anyway, I'll stick to OpenEdX now that I know Khan Academy open-source isn't attempting to do this.
